[package]
name = "Matter_Labs_Test_Project"
version = "0.1.0"
authors = ["Yehor Shapanov <yehor.shapanov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b-rs = "0.1.4"
rand = "0.7.0"